# Generated by Django 5.2.3 on 2025-06-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriptomoedaDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código da Moeda')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Moeda')),
                ('min_amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Valor Mínimo Transacionável')),
                ('max_amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Valor Máximo Transacionável')),
                ('network', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rede (Blockchain)')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da Moeda')),
                ('is_fiat', models.BooleanField(default=False, verbose_name='É Moeda Fiduciária?')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Detalhe de Criptomoeda',
                'verbose_name_plural': 'Detalhes de Criptomoedas',
                'ordering': ['name'],
            },
        ),
    ]
