# Generated by Django 5.2.3 on 2025-06-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomoedadetalhes',
            name='max_amount',
            field=models.CharField(verbose_name='Valor Máximo Transacionável'),
        ),
        migrations.AlterField(
            model_name='criptomoedadetalhes',
            name='min_amount',
            field=models.CharField(verbose_name='Valor Mínimo Transacionável'),
        ),
    ]
