# Generated by Django 5.2.3 on 2025-06-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_crypto', '0003_alter_criptomoedadetalhes_max_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomoedadetalhes',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True, verbose_name='Valor Máximo Transacionável'),
        ),
        migrations.AlterField(
            model_name='criptomoedadetalhes',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True, verbose_name='Valor Mínimo Transacionável'),
        ),
    ]
