# Generated by Django 5.2.3 on 2025-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='transacao_id_provedor',
            field=models.CharField(blank=True, help_text='ID da transação no gateway de pagamento (Pix TXID, CoinPayments txn_id, etc.)', max_length=255, null=True, unique=True, verbose_name='ID Transação Provedor Pagamento'),
        ),
    ]
